version: "3"
services:
  mysql:
    image: "mysql:5.7.10"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "pawnder"
      MYSQL_PASSWORD: "pawnder"
      MYSQL_DATABASE: "pawnder"
